#
# Copyright 2019-2022 Arcturus Networks, Inc.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += ucls1012a.o
obj-y += eth.o
obj-$(CONFIG_HX3_HUB_INIT) += hx3_init.o
obj-y += ../../freescale/common/
