#
# Copyright 2016, 2017 Arcturus Networks, Inc.
#           https://www.arcturusnetworks.com/products/ucls1012a/
# based on board/freescale/ls1012afrdm/Makefile
# original copyright follows:
# Copyright 2016 Freescale Semiconductor, Inc.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += ucls1012a.o
obj-y += eth.o
obj-y += ../../freescale/common/
